services:
  - type: web
    name: nextmeet-socket-server
    env: node
    plan: free
    rootDirectory: /
    buildCommand: npm install
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /healthcheck
    autoDeploy: true
